//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DesignerDatabaseModel", "FK_Lamp_Junction", "Junction", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Designer.Model.Junction), "Lamp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.Lamp), true)]

#endregion

namespace Designer.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DesignerDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DesignerDatabaseEntities object using the connection string found in the 'DesignerDatabaseEntities' section of the application configuration file.
        /// </summary>
        public DesignerDatabaseEntities() : base("name=DesignerDatabaseEntities", "DesignerDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DesignerDatabaseEntities object.
        /// </summary>
        public DesignerDatabaseEntities(string connectionString) : base(connectionString, "DesignerDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DesignerDatabaseEntities object.
        /// </summary>
        public DesignerDatabaseEntities(EntityConnection connection) : base(connection, "DesignerDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Junction> Junctions
        {
            get
            {
                if ((_Junctions == null))
                {
                    _Junctions = base.CreateObjectSet<Junction>("Junctions");
                }
                return _Junctions;
            }
        }
        private ObjectSet<Junction> _Junctions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lamp> Lamps
        {
            get
            {
                if ((_Lamps == null))
                {
                    _Lamps = base.CreateObjectSet<Lamp>("Lamps");
                }
                return _Lamps;
            }
        }
        private ObjectSet<Lamp> _Lamps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Junctions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJunctions(Junction junction)
        {
            base.AddObject("Junctions", junction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lamps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLamps(Lamp lamp)
        {
            base.AddObject("Lamps", lamp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DesignerDatabaseModel", Name="Junction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Junction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Junction object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Junction CreateJunction(global::System.Int32 id)
        {
            Junction junction = new Junction();
            junction.ID = id;
            return junction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JunctionName
        {
            get
            {
                return _JunctionName;
            }
            set
            {
                OnJunctionNameChanging(value);
                ReportPropertyChanging("JunctionName");
                _JunctionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JunctionName");
                OnJunctionNameChanged();
            }
        }
        private global::System.String _JunctionName;
        partial void OnJunctionNameChanging(global::System.String value);
        partial void OnJunctionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Lat
        {
            get
            {
                return _Lat;
            }
            set
            {
                OnLatChanging(value);
                ReportPropertyChanging("Lat");
                _Lat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lat");
                OnLatChanged();
            }
        }
        private Nullable<global::System.Double> _Lat;
        partial void OnLatChanging(Nullable<global::System.Double> value);
        partial void OnLatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Lng
        {
            get
            {
                return _Lng;
            }
            set
            {
                OnLngChanging(value);
                ReportPropertyChanging("Lng");
                _Lng = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lng");
                OnLngChanged();
            }
        }
        private Nullable<global::System.Double> _Lng;
        partial void OnLngChanging(Nullable<global::System.Double> value);
        partial void OnLngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expression
        {
            get
            {
                return _Expression;
            }
            set
            {
                OnExpressionChanging(value);
                ReportPropertyChanging("Expression");
                _Expression = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expression");
                OnExpressionChanged();
            }
        }
        private global::System.String _Expression;
        partial void OnExpressionChanging(global::System.String value);
        partial void OnExpressionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Map
        {
            get
            {
                return _Map;
            }
            set
            {
                OnMapChanging(value);
                ReportPropertyChanging("Map");
                _Map = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Map");
                OnMapChanged();
            }
        }
        private global::System.String _Map;
        partial void OnMapChanging(global::System.String value);
        partial void OnMapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DesignerDatabaseModel", "FK_Lamp_Junction", "Lamp")]
        public EntityCollection<Lamp> Lamps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lamp>("DesignerDatabaseModel.FK_Lamp_Junction", "Lamp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lamp>("DesignerDatabaseModel.FK_Lamp_Junction", "Lamp", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DesignerDatabaseModel", Name="Lamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lamp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Lamp CreateLamp(global::System.Int32 id)
        {
            Lamp lamp = new Lamp();
            lamp.ID = id;
            return lamp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LampID
        {
            get
            {
                return _LampID;
            }
            set
            {
                OnLampIDChanging(value);
                ReportPropertyChanging("LampID");
                _LampID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LampID");
                OnLampIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LampID;
        partial void OnLampIDChanging(Nullable<global::System.Int32> value);
        partial void OnLampIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private Nullable<global::System.Int32> _X;
        partial void OnXChanging(Nullable<global::System.Int32> value);
        partial void OnXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Y
        {
            get
            {
                return _Y;
            }
            set
            {
                OnYChanging(value);
                ReportPropertyChanging("Y");
                _Y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Y");
                OnYChanged();
            }
        }
        private Nullable<global::System.Int32> _Y;
        partial void OnYChanging(Nullable<global::System.Int32> value);
        partial void OnYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Direction
        {
            get
            {
                return _Direction;
            }
            set
            {
                OnDirectionChanging(value);
                ReportPropertyChanging("Direction");
                _Direction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Direction");
                OnDirectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Direction;
        partial void OnDirectionChanging(Nullable<global::System.Int32> value);
        partial void OnDirectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expression
        {
            get
            {
                return _Expression;
            }
            set
            {
                OnExpressionChanging(value);
                ReportPropertyChanging("Expression");
                _Expression = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expression");
                OnExpressionChanged();
            }
        }
        private global::System.String _Expression;
        partial void OnExpressionChanging(global::System.String value);
        partial void OnExpressionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JunctionID
        {
            get
            {
                return _JunctionID;
            }
            set
            {
                OnJunctionIDChanging(value);
                ReportPropertyChanging("JunctionID");
                _JunctionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JunctionID");
                OnJunctionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _JunctionID;
        partial void OnJunctionIDChanging(Nullable<global::System.Int32> value);
        partial void OnJunctionIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DesignerDatabaseModel", "FK_Lamp_Junction", "Junction")]
        public Junction Junction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Junction>("DesignerDatabaseModel.FK_Lamp_Junction", "Junction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Junction>("DesignerDatabaseModel.FK_Lamp_Junction", "Junction").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Junction> JunctionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Junction>("DesignerDatabaseModel.FK_Lamp_Junction", "Junction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Junction>("DesignerDatabaseModel.FK_Lamp_Junction", "Junction", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
