//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SapScadaDatabaseModel", "FK_IOTag_Device", "Device", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Designer.Model.Device), "IOTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.IOTag), true)]
[assembly: EdmRelationshipAttribute("SapScadaDatabaseModel", "FK_SystemEvent_Device", "Device", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Designer.Model.Device), "SystemEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.SystemEvent), true)]
[assembly: EdmRelationshipAttribute("SapScadaDatabaseModel", "FK_IOTagValue_IOTag", "IOTag", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Designer.Model.IOTag), "IOTagValue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.IOTagValue), true)]
[assembly: EdmRelationshipAttribute("SapScadaDatabaseModel", "FK_UserRight_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Designer.Model.User), "UserRight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.UserRight), true)]
[assembly: EdmRelationshipAttribute("SapScadaDatabaseModel", "FK_AlarmTag_IOTag", "IOTag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Designer.Model.IOTag), "AlarmTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.AlarmTag), true)]
[assembly: EdmRelationshipAttribute("SapScadaDatabaseModel", "FK_AlarmTagValue_AlarmTag", "AlarmTag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Designer.Model.AlarmTag), "AlarmTagValue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Designer.Model.AlarmTagValue), true)]

#endregion

namespace Designer.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SapScadaDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SapScadaDatabaseEntities object using the connection string found in the 'SapScadaDatabaseEntities' section of the application configuration file.
        /// </summary>
        public SapScadaDatabaseEntities() : base("name=SapScadaDatabaseEntities", "SapScadaDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SapScadaDatabaseEntities object.
        /// </summary>
        public SapScadaDatabaseEntities(string connectionString) : base(connectionString, "SapScadaDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SapScadaDatabaseEntities object.
        /// </summary>
        public SapScadaDatabaseEntities(EntityConnection connection) : base(connection, "SapScadaDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Device> Devices
        {
            get
            {
                if ((_Devices == null))
                {
                    _Devices = base.CreateObjectSet<Device>("Devices");
                }
                return _Devices;
            }
        }
        private ObjectSet<Device> _Devices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IOTag> IOTags
        {
            get
            {
                if ((_IOTags == null))
                {
                    _IOTags = base.CreateObjectSet<IOTag>("IOTags");
                }
                return _IOTags;
            }
        }
        private ObjectSet<IOTag> _IOTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IOTagValue> IOTagValues
        {
            get
            {
                if ((_IOTagValues == null))
                {
                    _IOTagValues = base.CreateObjectSet<IOTagValue>("IOTagValues");
                }
                return _IOTagValues;
            }
        }
        private ObjectSet<IOTagValue> _IOTagValues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Server> Servers
        {
            get
            {
                if ((_Servers == null))
                {
                    _Servers = base.CreateObjectSet<Server>("Servers");
                }
                return _Servers;
            }
        }
        private ObjectSet<Server> _Servers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemEvent> SystemEvents
        {
            get
            {
                if ((_SystemEvents == null))
                {
                    _SystemEvents = base.CreateObjectSet<SystemEvent>("SystemEvents");
                }
                return _SystemEvents;
            }
        }
        private ObjectSet<SystemEvent> _SystemEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserRight> UserRights
        {
            get
            {
                if ((_UserRights == null))
                {
                    _UserRights = base.CreateObjectSet<UserRight>("UserRights");
                }
                return _UserRights;
            }
        }
        private ObjectSet<UserRight> _UserRights;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AlarmTag> AlarmTags
        {
            get
            {
                if ((_AlarmTags == null))
                {
                    _AlarmTags = base.CreateObjectSet<AlarmTag>("AlarmTags");
                }
                return _AlarmTags;
            }
        }
        private ObjectSet<AlarmTag> _AlarmTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AlarmTagValue> AlarmTagValues
        {
            get
            {
                if ((_AlarmTagValues == null))
                {
                    _AlarmTagValues = base.CreateObjectSet<AlarmTagValue>("AlarmTagValues");
                }
                return _AlarmTagValues;
            }
        }
        private ObjectSet<AlarmTagValue> _AlarmTagValues;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Devices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDevices(Device device)
        {
            base.AddObject("Devices", device);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IOTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIOTags(IOTag iOTag)
        {
            base.AddObject("IOTags", iOTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IOTagValues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIOTagValues(IOTagValue iOTagValue)
        {
            base.AddObject("IOTagValues", iOTagValue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Servers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServers(Server server)
        {
            base.AddObject("Servers", server);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemEvents(SystemEvent systemEvent)
        {
            base.AddObject("SystemEvents", systemEvent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserRights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserRights(UserRight userRight)
        {
            base.AddObject("UserRights", userRight);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AlarmTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlarmTags(AlarmTag alarmTag)
        {
            base.AddObject("AlarmTags", alarmTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AlarmTagValues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlarmTagValues(AlarmTagValue alarmTagValue)
        {
            base.AddObject("AlarmTagValues", alarmTagValue);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="AlarmTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AlarmTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AlarmTag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="iOTagId">Initial value of the IOTagId property.</param>
        /// <param name="updateRating">Initial value of the UpdateRating property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static AlarmTag CreateAlarmTag(global::System.Int32 id, global::System.String name, global::System.Int32 type, global::System.Int32 iOTagId, global::System.Int32 updateRating, global::System.Boolean isActive)
        {
            AlarmTag alarmTag = new AlarmTag();
            alarmTag.Id = id;
            alarmTag.Name = name;
            alarmTag.Type = type;
            alarmTag.IOTagId = iOTagId;
            alarmTag.UpdateRating = updateRating;
            alarmTag.IsActive = isActive;
            return alarmTag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IOTagId
        {
            get
            {
                return _IOTagId;
            }
            set
            {
                OnIOTagIdChanging(value);
                ReportPropertyChanging("IOTagId");
                _IOTagId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IOTagId");
                OnIOTagIdChanged();
            }
        }
        private global::System.Int32 _IOTagId;
        partial void OnIOTagIdChanging(global::System.Int32 value);
        partial void OnIOTagIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
             //   ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Int32> _Value;
        partial void OnValueChanging(Nullable<global::System.Int32> value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AlarmOnWhen
        {
            get
            {
                return _AlarmOnWhen;
            }
            set
            {
                OnAlarmOnWhenChanging(value);
                ReportPropertyChanging("AlarmOnWhen");
                _AlarmOnWhen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlarmOnWhen");
                OnAlarmOnWhenChanged();
            }
        }
        private Nullable<global::System.Int32> _AlarmOnWhen;
        partial void OnAlarmOnWhenChanging(Nullable<global::System.Int32> value);
        partial void OnAlarmOnWhenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStamp;
        partial void OnTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UpdateRating
        {
            get
            {
                return _UpdateRating;
            }
            set
            {
                OnUpdateRatingChanging(value);
                ReportPropertyChanging("UpdateRating");
                _UpdateRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateRating");
                OnUpdateRatingChanged();
            }
        }
        private global::System.Int32 _UpdateRating;
        partial void OnUpdateRatingChanging(global::System.Int32 value);
        partial void OnUpdateRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_AlarmTag_IOTag", "IOTag")]
        public IOTag IOTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IOTag>("SapScadaDatabaseModel.FK_AlarmTag_IOTag", "IOTag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IOTag>("SapScadaDatabaseModel.FK_AlarmTag_IOTag", "IOTag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<IOTag> IOTagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IOTag>("SapScadaDatabaseModel.FK_AlarmTag_IOTag", "IOTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<IOTag>("SapScadaDatabaseModel.FK_AlarmTag_IOTag", "IOTag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_AlarmTagValue_AlarmTag", "AlarmTagValue")]
        public EntityCollection<AlarmTagValue> AlarmTagValues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AlarmTagValue>("SapScadaDatabaseModel.FK_AlarmTagValue_AlarmTag", "AlarmTagValue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AlarmTagValue>("SapScadaDatabaseModel.FK_AlarmTagValue_AlarmTag", "AlarmTagValue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="AlarmTagValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AlarmTagValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AlarmTagValue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="timeStampOn">Initial value of the TimeStampOn property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="alarmTagId">Initial value of the AlarmTagId property.</param>
        public static AlarmTagValue CreateAlarmTagValue(global::System.Int32 id, global::System.Int32 value, global::System.DateTime timeStampOn, global::System.Int32 status, global::System.Int32 alarmTagId)
        {
            AlarmTagValue alarmTagValue = new AlarmTagValue();
            alarmTagValue.Id = id;
            alarmTagValue.Value = value;
            alarmTagValue.TimeStampOn = timeStampOn;
            alarmTagValue.Status = status;
            alarmTagValue.AlarmTagId = alarmTagId;
            return alarmTagValue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int32 _Value;
        partial void OnValueChanging(global::System.Int32 value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeStampOn
        {
            get
            {
                return _TimeStampOn;
            }
            set
            {
                OnTimeStampOnChanging(value);
                ReportPropertyChanging("TimeStampOn");
                _TimeStampOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampOn");
                OnTimeStampOnChanged();
            }
        }
        private global::System.DateTime _TimeStampOn;
        partial void OnTimeStampOnChanging(global::System.DateTime value);
        partial void OnTimeStampOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampOff
        {
            get
            {
                return _TimeStampOff;
            }
            set
            {
                OnTimeStampOffChanging(value);
                ReportPropertyChanging("TimeStampOff");
                _TimeStampOff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampOff");
                OnTimeStampOffChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampOff;
        partial void OnTimeStampOffChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampOffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlarmTagId
        {
            get
            {
                return _AlarmTagId;
            }
            set
            {
                OnAlarmTagIdChanging(value);
                ReportPropertyChanging("AlarmTagId");
                _AlarmTagId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlarmTagId");
                OnAlarmTagIdChanged();
            }
        }
        private global::System.Int32 _AlarmTagId;
        partial void OnAlarmTagIdChanging(global::System.Int32 value);
        partial void OnAlarmTagIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_AlarmTagValue_AlarmTag", "AlarmTag")]
        public AlarmTag AlarmTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AlarmTag>("SapScadaDatabaseModel.FK_AlarmTagValue_AlarmTag", "AlarmTag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AlarmTag>("SapScadaDatabaseModel.FK_AlarmTagValue_AlarmTag", "AlarmTag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AlarmTag> AlarmTagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AlarmTag>("SapScadaDatabaseModel.FK_AlarmTagValue_AlarmTag", "AlarmTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AlarmTag>("SapScadaDatabaseModel.FK_AlarmTagValue_AlarmTag", "AlarmTag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="Device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Device : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Device CreateDevice(global::System.Int32 id)
        {
            Device device = new Device();
            device.ID = id;
            return device;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private Nullable<global::System.Int32> _Port;
        partial void OnPortChanging(Nullable<global::System.Int32> value);
        partial void OnPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Driver
        {
            get
            {
                return _Driver;
            }
            set
            {
                OnDriverChanging(value);
                ReportPropertyChanging("Driver");
                _Driver = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Driver");
                OnDriverChanged();
            }
        }
        private global::System.String _Driver;
        partial void OnDriverChanging(global::System.String value);
        partial void OnDriverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_IOTag_Device", "IOTag")]
        public EntityCollection<IOTag> IOTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IOTag>("SapScadaDatabaseModel.FK_IOTag_Device", "IOTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IOTag>("SapScadaDatabaseModel.FK_IOTag_Device", "IOTag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_SystemEvent_Device", "SystemEvent")]
        public EntityCollection<SystemEvent> SystemEvents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SystemEvent>("SapScadaDatabaseModel.FK_SystemEvent_Device", "SystemEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SystemEvent>("SapScadaDatabaseModel.FK_SystemEvent_Device", "SystemEvent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="IOTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IOTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IOTag object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static IOTag CreateIOTag(global::System.Int32 id)
        {
            IOTag iOTag = new IOTag();
            iOTag.ID = id;
            return iOTag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DataType
        {
            get
            {
                return _DataType;
            }
            set
            {
                OnDataTypeChanging(value);
                ReportPropertyChanging("DataType");
                _DataType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataType");
                OnDataTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _DataType;
        partial void OnDataTypeChanging(Nullable<global::System.Int32> value);
        partial void OnDataTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                OnDeviceIDChanging(value);
                ReportPropertyChanging("DeviceID");
                _DeviceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviceID");
                OnDeviceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DeviceID;
        partial void OnDeviceIDChanging(Nullable<global::System.Int32> value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStamp;
        partial void OnTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quality
        {
            get
            {
                return _Quality;
            }
            set
            {
                OnQualityChanging(value);
                ReportPropertyChanging("Quality");
                _Quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quality");
                OnQualityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quality;
        partial void OnQualityChanging(Nullable<global::System.Int32> value);
        partial void OnQualityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdateRating
        {
            get
            {
                return _UpdateRating;
            }
            set
            {
                OnUpdateRatingChanging(value);
                ReportPropertyChanging("UpdateRating");
                _UpdateRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateRating");
                OnUpdateRatingChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdateRating;
        partial void OnUpdateRatingChanging(Nullable<global::System.Int32> value);
        partial void OnUpdateRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsStoreToLog
        {
            get
            {
                return _IsStoreToLog;
            }
            set
            {
                OnIsStoreToLogChanging(value);
                ReportPropertyChanging("IsStoreToLog");
                _IsStoreToLog = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsStoreToLog");
                OnIsStoreToLogChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsStoreToLog;
        partial void OnIsStoreToLogChanging(Nullable<global::System.Boolean> value);
        partial void OnIsStoreToLogChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_IOTag_Device", "Device")]
        public Device Device
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("SapScadaDatabaseModel.FK_IOTag_Device", "Device").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("SapScadaDatabaseModel.FK_IOTag_Device", "Device").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Device> DeviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("SapScadaDatabaseModel.FK_IOTag_Device", "Device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Device>("SapScadaDatabaseModel.FK_IOTag_Device", "Device", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_IOTagValue_IOTag", "IOTagValue")]
        public EntityCollection<IOTagValue> IOTagValues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IOTagValue>("SapScadaDatabaseModel.FK_IOTagValue_IOTag", "IOTagValue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IOTagValue>("SapScadaDatabaseModel.FK_IOTagValue_IOTag", "IOTagValue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_AlarmTag_IOTag", "AlarmTag")]
        public EntityCollection<AlarmTag> AlarmTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AlarmTag>("SapScadaDatabaseModel.FK_AlarmTag_IOTag", "AlarmTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AlarmTag>("SapScadaDatabaseModel.FK_AlarmTag_IOTag", "AlarmTag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="IOTagValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IOTagValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IOTagValue object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static IOTagValue CreateIOTagValue(global::System.Int32 id)
        {
            IOTagValue iOTagValue = new IOTagValue();
            iOTagValue.ID = id;
            return iOTagValue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IOTagID
        {
            get
            {
                return _IOTagID;
            }
            set
            {
                OnIOTagIDChanging(value);
                ReportPropertyChanging("IOTagID");
                _IOTagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IOTagID");
                OnIOTagIDChanged();
            }
        }
        private Nullable<global::System.Int32> _IOTagID;
        partial void OnIOTagIDChanging(Nullable<global::System.Int32> value);
        partial void OnIOTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStamp;
        partial void OnTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quality
        {
            get
            {
                return _Quality;
            }
            set
            {
                OnQualityChanging(value);
                ReportPropertyChanging("Quality");
                _Quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quality");
                OnQualityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quality;
        partial void OnQualityChanging(Nullable<global::System.Int32> value);
        partial void OnQualityChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_IOTagValue_IOTag", "IOTag")]
        public IOTag IOTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IOTag>("SapScadaDatabaseModel.FK_IOTagValue_IOTag", "IOTag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IOTag>("SapScadaDatabaseModel.FK_IOTagValue_IOTag", "IOTag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<IOTag> IOTagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IOTag>("SapScadaDatabaseModel.FK_IOTagValue_IOTag", "IOTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<IOTag>("SapScadaDatabaseModel.FK_IOTagValue_IOTag", "IOTag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="Server")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Server : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Server object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Server CreateServer(global::System.Int32 id)
        {
            Server server = new Server();
            server.ID = id;
            return server;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="SystemEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemEvent object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static SystemEvent CreateSystemEvent(global::System.Int32 id)
        {
            SystemEvent systemEvent = new SystemEvent();
            systemEvent.ID = id;
            return systemEvent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                OnDeviceIDChanging(value);
                ReportPropertyChanging("DeviceID");
                _DeviceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviceID");
                OnDeviceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DeviceID;
        partial void OnDeviceIDChanging(Nullable<global::System.Int32> value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                OnEventIDChanging(value);
                ReportPropertyChanging("EventID");
                _EventID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventID");
                OnEventIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EventID;
        partial void OnEventIDChanging(Nullable<global::System.Int32> value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EventSubID
        {
            get
            {
                return _EventSubID;
            }
            set
            {
                OnEventSubIDChanging(value);
                ReportPropertyChanging("EventSubID");
                _EventSubID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventSubID");
                OnEventSubIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EventSubID;
        partial void OnEventSubIDChanging(Nullable<global::System.Int32> value);
        partial void OnEventSubIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Time;
        partial void OnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Parameter
        {
            get
            {
                return _Parameter;
            }
            set
            {
                OnParameterChanging(value);
                ReportPropertyChanging("Parameter");
                _Parameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parameter");
                OnParameterChanged();
            }
        }
        private Nullable<global::System.Int32> _Parameter;
        partial void OnParameterChanging(Nullable<global::System.Int32> value);
        partial void OnParameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.String _Priority;
        partial void OnPriorityChanging(global::System.String value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsConfirm
        {
            get
            {
                return _IsConfirm;
            }
            set
            {
                OnIsConfirmChanging(value);
                ReportPropertyChanging("IsConfirm");
                _IsConfirm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsConfirm");
                OnIsConfirmChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsConfirm;
        partial void OnIsConfirmChanging(Nullable<global::System.Boolean> value);
        partial void OnIsConfirmChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_SystemEvent_Device", "Device")]
        public Device Device
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("SapScadaDatabaseModel.FK_SystemEvent_Device", "Device").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("SapScadaDatabaseModel.FK_SystemEvent_Device", "Device").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Device> DeviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("SapScadaDatabaseModel.FK_SystemEvent_Device", "Device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Device>("SapScadaDatabaseModel.FK_SystemEvent_Device", "Device", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static User CreateUser(global::System.Int32 id)
        {
            User user = new User();
            user.ID = id;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_UserRight_User", "UserRight")]
        public EntityCollection<UserRight> UserRights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserRight>("SapScadaDatabaseModel.FK_UserRight_User", "UserRight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserRight>("SapScadaDatabaseModel.FK_UserRight_User", "UserRight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SapScadaDatabaseModel", Name="UserRight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserRight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserRight object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static UserRight CreateUserRight(global::System.Int32 id)
        {
            UserRight userRight = new UserRight();
            userRight.ID = id;
            return userRight;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Privilege
        {
            get
            {
                return _Privilege;
            }
            set
            {
                OnPrivilegeChanging(value);
                ReportPropertyChanging("Privilege");
                _Privilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Privilege");
                OnPrivilegeChanged();
            }
        }
        private Nullable<global::System.Int32> _Privilege;
        partial void OnPrivilegeChanging(Nullable<global::System.Int32> value);
        partial void OnPrivilegeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SapScadaDatabaseModel", "FK_UserRight_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SapScadaDatabaseModel.FK_UserRight_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SapScadaDatabaseModel.FK_UserRight_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SapScadaDatabaseModel.FK_UserRight_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SapScadaDatabaseModel.FK_UserRight_User", "User", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
